# Generated by Django 4.2.27 on 2026-01-22 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(help_text='Type of IOT device', max_length=100)),
                ('mac_id', models.CharField(help_text='Device MAC address', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', help_text='Device status', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True, help_text='Device registration timestamp')),
            ],
            options={
                'verbose_name': 'IOT Device',
                'verbose_name_plural': 'IOT Devices',
                'db_table': 'iot_devices',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text="User's display name", max_length=150)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True)),
                ('phone', models.CharField(help_text="User's phone number", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Account creation timestamp')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField(help_text='Pothole depth in cm', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Severity level', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Pothole image', null=True, upload_to='potholes/')),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='Detection timestamp')),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('fixed', 'Fixed'), ('ignored', 'Ignored')], default='unresolved', help_text='Resolution status', max_length=20)),
                ('latitude', models.FloatField(help_text='Latitude coordinate', validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(help_text='Longitude coordinate', validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('address', models.CharField(blank=True, help_text='Human-readable address', max_length=500, null=True)),
                ('device', models.ForeignKey(help_text='Device that detected the pothole', on_delete=django.db.models.deletion.CASCADE, related_name='detected_potholes', to='app.iotdevice')),
                ('user', models.ForeignKey(help_text='User associated with detection', on_delete=django.db.models.deletion.CASCADE, related_name='reported_potholes', to='app.user')),
            ],
            options={
                'verbose_name': 'Pothole',
                'verbose_name_plural': 'Potholes',
                'db_table': 'potholes',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='owner',
            field=models.ForeignKey(help_text='User ID of device owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_devices', to='app.user'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='registered_by',
            field=models.ForeignKey(help_text='Admin/owner who registered device', on_delete=django.db.models.deletion.CASCADE, related_name='registered_devices', to='app.user'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_text', models.TextField(help_text='Alert message content')),
                ('alert_type', models.CharField(choices=[('warning', 'Warning'), ('info', 'Info'), ('emergency', 'Emergency')], help_text='Type of alert', max_length=20)),
                ('alert_time', models.DateTimeField(auto_now_add=True, help_text='Alert creation timestamp')),
                ('distance', models.FloatField(help_text='Distance to pothole in meters', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('pothole', models.ForeignKey(help_text='Associated pothole', on_delete=django.db.models.deletion.CASCADE, related_name='pothole_alerts', to='app.pothole')),
                ('user', models.ForeignKey(help_text='User receiving the alert', on_delete=django.db.models.deletion.CASCADE, related_name='user_alerts', to='app.user')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alerts',
                'ordering': ['-alert_time'],
            },
        ),
    ]
