# Generated by Django 4.2.23 on 2026-01-22 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotholeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Uploaded pothole image', upload_to='pothole_uploads/')),
                ('latitude', models.FloatField(blank=True, help_text='Latitude at time of upload', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude at time of upload', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Upload timestamp')),
                ('device', models.ForeignKey(blank=True, help_text='Device that uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='app.iotdevice')),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to='app.user')),
            ],
            options={
                'verbose_name': 'Pothole Image',
                'verbose_name_plural': 'Pothole Images',
                'db_table': 'pothole_images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
