# Generated by Django 4.2.23 on 2026-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_potholeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='hashed_placeholder', help_text='Hashed password', max_length=128),
            preserve_default=False,
        ),
    ]
