# Generated by Django 4.2.27 on 2026-01-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PotholeImage',
        ),
    ]
