# Generated by Django 4.2.27 on 2026-02-01 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_potholeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAPI',
            fields=[
            ],
            options={
                'verbose_name': 'Login API (Swagger)',
                'verbose_name_plural': 'Login API (Swagger)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app.user',),
        ),
    ]
