# Generated by Django 4.2.27 on 2026-02-07 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_loginapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='esp_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Current IP of the ESP8266/ESP32', null=True),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='last_latitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='last_longitude',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
